### ISSUE TITLE
LUA Error on entering game and also when reloading UI

### ISSUE THREAD

**Issue by DiscipleDarkfriend** [donniedice/BLU#1]
7x Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "MAJOR_FACTION_RENOWN_LEVEL_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:137: in function `RegisterEvent'
[string "@Interface\AddOns\BLU\Core.lua"]:18: in function <Interface\AddOns\BLU\Core.lua:15>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:66: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:626: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:611>

**Comment by DiscipleDarkfriend** [comment]
Forgot to mention this is the WOTLK C version.

**Comment by donniedice** [comment]
I just pushed v0.0.13. 
- Fixed - MAJOR_FACTION_RENOWN_LEVEL_CHANGED error in WotLK/BC/SoM
- Split - Code Base for Retail/Classic Clients

This should have fixed the error you were getting.

**Comment by donniedice** [comment]
> > I just pushed v0.0.13.
> > 
> > * Fixed - MAJOR_FACTION_RENOWN_LEVEL_CHANGED error in WotLK/BC/SoM
> > * Split - Code Base for Retail/Classic Clients
> > 
> > This should have fixed the error you were getting.
> 
> You are above and beyond awesome fam, Thank you ! <3


You are very welcome! Thanks for using my Addon! I appreciate you!
