### ISSUE TITLE
[4.6.0] Wrong sounds for quest accepted / quest completed

### ISSUE THREAD

**Issue by SoulCookie** [donniedice/BLU#10]
Hi. As of the v4.6.0 release yesterday, my [default] "Quest Accepted!" and "Quest Complete!" sounds are, incorrectly, both playing the default WoW achievement sound.

**Comment by donniedice** [comment]
Fixed!

**Comment by MelchiorGaspar** [comment]
ooh wow some one else already reported the issue I am having too..
nice.. 
when might the fixed version get pushed out to CurseForge?
please and thx.

**Comment by MelchiorGaspar** [comment]
ooh I just saw the new email notification for BLU.. ty.

**Comment by donniedice** [comment]
Yeah... sorry about that... somehow missed the logic for the hard-coded soundIDs on the restructure :X
