### ISSUE TITLE
Kill sound + unreal tournament audio request

### ISSUE THREAD

**Issue by tylertylerday** [donniedice/BLU#12]
Just wanted to request pvp kill sound customizations with sounds from the classic Unreal Tournament like "Double killll" ...etc. 

Thanks!!

**Comment by donniedice** [comment]
This could turn into a larger project. I have a few idea to split this addon. Most of the functionality that BLU provides, can be achieved with weakauras and dbm.. however.. what makes BLU stand out is my focus on ease-of-use and base game integration. The reason people don't use these other addons to achieve the things BLU does, ie, changing event sounds, is that it's not very easy or straight-forward. 

Having a pvp oriented version of BLU is in the time-line.. as well as build-out for an addon that allows for sounds on a per-reputation/renown-faction basis. Another fork would be better menu sounds. 

Again, this will be a bit of work, tracking and resetting kill sprees etc.. but it does sound like fun, and I can definitely see this being added somewhere along the line.

Adding an event trigger for pvp kill, and a few pvp-sounding-sound files would be a faster implementation if you have suggestions for 'single kill' sounds.
