### ISSUE TITLE
new error message, retail-WoW (v11.0.2)

### ISSUE THREAD

**Issue by MelchiorGaspar** [donniedice/BLU#14]
just started the war within island area and when attempting to turn in the quest,
[Secure the Breach]
it gave me the following error message in BugSack.
BLU addon version v4.7.2

1x BLU/data/retail.lua:32: attempt to call global 'SelectSound' (a nil value)
[string "@BLU/data/retail.lua"]:32: in function `?'
[string "@BLU/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...BLU/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@BLU/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...BLU/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BLU/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BLU/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <BLU/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 defaults = <table> {
 }
 functionsHalted = false
 modules = <table> {
 }
 baseName = "BLU"
 showWelcomeMessage = true
 defaultModuleState = true
 haltTimerRunning = false
 chatFrameHooked = false
 db = <table> {
 }
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 optionsFrame = Frame {
 }
 options = <table> {
 }
 name = "BLU"
 orderedModules = <table> {
 }
 debugMode = false
}
(*temporary) = nil
(*temporary) = 21
(*temporary) = "attempt to call global 'SelectSound' (a nil value)"

**Comment by MelchiorGaspar** [comment]
just grabbed v4.7.3 of BLU.. thx for fixing issues so quickly. :D

**Comment by donniedice** [comment]
Oh hey! Not-a-problem! Dude.... I can't play WoW without this addon anymore... u_u

**Comment by MelchiorGaspar** [comment]
lol nice!
I always play the Final Fantasy level up sound, in place of the WoW level up sound...
sounds way cooler. :D
