### ISSUE TITLE
4.7.3 sounds still broken

### ISSUE THREAD

**Issue by SoulCookie** [donniedice/BLU#16]
re: #15

**Comment by donniedice** [comment]
v4.7.4 is on the way, I love late night code sessions... and I'm almost to a point with this where I won't need a sanity check before code pushes.

**Comment by donniedice** [comment]
Also, heads up.. I just _think_ I fixed it.. my internet is out due to weather until 9pm. I'm barley able to get these tags pushes out >_<

**Comment by SoulCookie** [comment]
Sounds good. Thanks for the quick fixes. 😊👍

**Comment by donniedice** [comment]
Was able to login and test, v4.7.4 had scoping issues. v4.7.5 has resolved this issue.
