### ISSUE TITLE
Welcome Text

### ISSUE THREAD

**Issue by GingersnapsOut** [donniedice/BLU#17]
everytime i take a portal i get the welcome text:

[00:26] [BLU] Addon Loaded! Type /blu to open options panel or /blu help for more commands. 
[00:27] Loot Specialization set to: Assassination 
[00:27] [BLU] Addon Loaded! Type /blu to open options panel or /blu help for more commands. 

is it possible to - or get rid of it or an option to disable it at all.
or that it only shows you once on login and not when taking portals?
or has it do to with deleting the lua.bak files in the wtf folder?

**Comment by donniedice** [comment]
/blu welcome should disable that

Sent from Proton Mail Android

-------- Original Message --------

**Comment by donniedice** [comment]
Ill streamline this functionality in v5.

**Comment by donniedice** [comment]
If you get back to this, please let me know some more information.

Game Version
AddOn Version

- Have you used the "/blu welcome" command to disable the message?

**Comment by donniedice** [comment]
Come back to this if you're still having issues, I'm going to close for now.
