### ISSUE TITLE
got a new error on level up, BLU v5.0

### ISSUE THREAD

**Issue by MelchiorGaspar** [donniedice/BLU#18]
1x BLU/data/utils.lua:21: attempt to concatenate local 'eventName' (a nil value)
[string "@BLU/data/utils.lua"]:21: in function `HandleEvent'
[string "@BLU/data/core.lua"]:10: in function `?'
[string "@AutoProfitX2/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...tX2/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AutoProfitX2/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...tX2/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AutoProfitX2/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@AutoProfitX2/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...dOns/AutoProfitX2/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 functionsHalted = false
 EnableModule = <function> defined @AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 baseName = "BLU"
 IterateEmbeds = <function> defined @AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 ResumeOperations = <function> defined @BLU/data/utils.lua:79
 AssignGroupColors = <function> defined @BLU/data/initialization.lua:230
 HandlePlayerEnteringWorld = <function> defined @BLU/data/utils.lua:38
 HandleDelveLevelUp = <function> defined @BLU/data/core.lua:178
 showWelcomeMessage = true
 HandleEvent = <function> defined @BLU/data/utils.lua:20
 TestSound = <function> defined @BLU/data/utils.lua:215
 ToggleWelcomeMessage = <function> defined @BLU/data/utils.lua:136
 defaultModuleState = true
 TestAchievementSound = <function> defined @BLU/data/core.lua:197
 IsEnabled = <function> defined @AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 HandlePetBattleLevelChanged = <function> defined @BLU/data/core.lua:38
 HandleRenownLevelChanged = <function> defined @BLU/data/core.lua:33
 DisableModule = <function> defined @AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 IsGroupCompatibleWithVersion = <function> defined @BLU/data/initialization.lua:170
 TestDelveLevelUpSound = <function> defined @BLU/data/core.lua:205
 GetGameVersion = <function> defined @BLU/data/initialization.lua:26
 RegisterMessage = <function> defined @AutoProfitX2/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 GetArgs = <function> defined @AutoProfitX2/libs/AceConsole-3.0/AceConsole-3.0.lua:140
 optionsRegistered = true
 db = <table> {
 }
 PlaySelectedSound = <function> defined @BLU/data/utils.lua:227
 SetEnabledState = <function> defined @AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 enabledState = true
 RegisterEvent = <function> defined @AutoProfitX2/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 HandlePlayerLevelUp = <function> defined @BLU/data/core.lua:8
 DelveLevelUpChatFrameHook = <function> defined @BLU/data/core.lua:158
 HandlePerksActivityCompleted = <function> defined @BLU/data/core.lua:43
 IterateModules = <function> defined @AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 sortedOptions = <table> {
 }
 DebugMessage = <function> defined @BLU/data/utils.lua:150
 TestBattlePetLevelSound = <function> defined @BLU/data/core.lua:201
 HandleQuestTurnedIn = <function> defined @BLU/data/core.lua:18
 OnInitialize = <function> defined @BLU/data/initialization.lua:77
 RegisterChatCommand = <function> defined @AutoProfitX2/libs/AceConsole-3.0/AceConsole-3.0.lua:81
 GetModule = <function> defined @AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 defaultModuleLibraries = <table> {
 }
 TestRepSound = <function> defined @BLU/data/core.lua:233
 TestPostSound = <function> defined @BLU/data/core.lua:217
 UnregisterChatCommand = <function> defined @AutoProfitX2/libs/AceConsole-3.0/AceConsole-3.0.lua:107
 options = <table> {
 }
 recentReputationRanks = <table> {
 }
 countdownRunning = false
 chatFrameHooked = true
 GetName = <function> defined @AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 optionsFrame = Frame {
 }
 defaults = <table> {
 }
 name = "BLU"
 TestRenownSound = <function> defined @BLU/data/core.lua:229
 SetDefaultModulePrototype = <function> defined @AutoProfitX2/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 V

**Comment by donniedice** [comment]
https://github.com/donniedice/BLU/releases/tag/v5.0.1

---
## v5.0.1

```
- Fixed - Error in Level-Up! Localization - [core.lua]

**Comment by MelchiorGaspar** [comment]
Thank you.
