### ISSUE TITLE
[Feature Request] All Objectives Complete

### ISSUE THREAD

**Issue by webdevdave** [donniedice/BLU#23]
I touched on this in my other post. But I thought it deserved its own feature request. 😁

I'd love it if you could add the ability to add a sound when all objectives in a quest are complete _(i.e. **10/10 Bandits Killed** or when you fill a meter for like disrupting an area, etc.)_. 
It caters to the lazy in me of not wanting to keep my eye on the objectives and just KILL KILL KILL until I hear the horns of victory! 😈

Thanks, and keep up the awesome addon!

**Comment by donniedice** [comment]
Ok, so I have big plans for BLU | Bettle Level Up! - This is part of the road map. I haven't fully decided how I'm going to lay it all out yet. I have a menu re-design for v6.0.0 in the works. and with that will come some new and cool stuff, _including objective sounds._
