### ISSUE TITLE
[5.1.0] No event sounds at all

### ISSUE THREAD

**Issue by SoulCookie** [donniedice/BLU#24]
The current release doesn't appear to be working; I hear the appropriate sounds in the BLU control panel preview, but they're not firing during play. 

I've not encountered all of them, but there've been enough that I'm confident in assuming none of them are working. The events I've had where no sound played:

- Battle Pet Level-Up!
- Level-Up!
- Quest Accepted!
- Quest Complete!

**Comment by donniedice** [comment]
Making big strides in the battle pet tracking. Ill have a fully working version soon. Sorry again I did some really unorganized code pushes around 4am lol.

For now v5.0.6 has everything except fully functional battle pet level sounds.Also, Im trying to get the broken versions archived.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by donniedice** [comment]
I think I got it. I'm still working out kinks in battle pet tracking.
---

**v5.1.1**
https://github.com/donniedice/BLU/releases/tag/v5.1.1

---

```
- Fixed - Multiple calls to `battlepets.lua` in TOC file causing redundant execution - [BLU.toc]
- Fixed - Login spam for pet level-up sounds after the halt timer expires - [battlepets.lua]
- Fixed - Broken event handlers causing incorrect sound triggers and event processing - [battlepets.lua]
