### ISSUE TITLE
No longer playing sounds

### ISSUE THREAD

**Issue by Psymon777** [donniedice/BLU#25]
It is no longer playing sounds for my achievements, and level ups.

**Comment by donniedice** [comment]
Fix is inc.
Sent from Proton Mail Android

-------- Original Message --------

**Comment by donniedice** [comment]
I think I got it. I'm still working out kinks in battle pet tracking.

---

**v5.1.1**
https://github.com/donniedice/BLU/releases/tag/v5.1.1

---

```
- Fixed - Multiple calls to `battlepets.lua` in TOC file causing redundant execution - [BLU.toc]
- Fixed - Login spam for pet level-up sounds after the halt timer expires - [battlepets.lua]
- Fixed - Broken event handlers causing incorrect sound triggers and event processing - [battlepets.lua]
