### ISSUE TITLE
[Feature Request] (sort of) Reverse/extract the Pet Battling level-up stuff

### ISSUE THREAD

**Issue by SoulCookie** [donniedice/BLU#28]
Hi. Sorry for yet another ticket, but with this one I'd like to **request/suggest that you remove the pet battling level-up stuff** from BLU, and maybe spin it off into its own separate-but-related thing.

It seems like it's been a lot of work and a lot of headache trying to get it to work, and (for me, at least) for not a lot of benefit.

**Comment by donniedice** [comment]
Probably should have did this from the jump. I took your advice and have a version pushed without the battlepets.lua, v5.1.4/v5.1.5
