### ISSUE TITLE
Addon does not load

### ISSUE THREAD

**Issue by Alternus1** [donniedice/BLU#29]
Errors:

Message: ...erface/AddOns/BLU/Libs/AceEvent-3.0/AceEvent-3.0.lua:13: Cannot find a library instance of "CallbackHandler-1.0".
Time: Mon Sep 30 21:21:56 2024
Count: 1
Stack: ...erface/AddOns/BLU/Libs/AceEvent-3.0/AceEvent-3.0.lua:13: Cannot find a library instance of "CallbackHandler-1.0".
[string "@Interface/AddOns/BLU/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/BLU/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:13: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "CallbackHandler-1.0"
silent = nil

-------------------------------------

Message: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
Time: Mon Sep 30 21:21:56 2024
Count: 1
Stack: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
[string "@Interface/AddOns/BLU/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/BLU/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:12: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "CallbackHandler-1.0"
silent = nil

----------------------------------------------

Message: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
Time: Mon Sep 30 21:21:56 2024
Count: 1
Stack: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
[string "@Interface/AddOns/BLU/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/BLU/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:12: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "CallbackHandler-1.0"
silent = nil

-------------------------------------------------

Message: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
Time: Mon Sep 30 21:21:56 2024
Count: 1
Stack: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
[string "@Interface/AddOns/BLU/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/BLU/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:12: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "CallbackHandler-1.0"
silent = nil

-----------------------------------------------------

Message: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
Time: Mon Sep 30 21:21:56 2024
Count: 1
Stack: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
[string "@Interface/AddOns/BLU/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/BLU/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:12: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "CallbackHandler-1.0"
silent = nil

----------------------------------------------------

Message: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
Time: Mon Sep 30 21:21:56 2024
Count: 1
Stack: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
[string "@Interface/AddOns/BLU/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/BLU/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:12: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "CallbackHandler-1.0"
silent = nil

--------------------------------------------------

Message: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
Time: Mon Sep 30 21:21:56 2024
Count: 1
Stack: ...-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
[string "@Interface/AddOns/BLU/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/BLU/Libs/AceConfig-3.0/AceConfigRegistry-3.0/AceConfigRegistry-3.0.lua"]:12: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "CallbackHandler-1.0"
silent = nil

**Comment by donniedice** [comment]
Will check after work. Thanks for the bug report.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by donniedice** [comment]
Ok, I am not currently able to re-produce this error. I will keep trying in the mean time.

Can you give me some more information?

Which addon Version?
Which WoW Version?

**Comment by donniedice** [comment]
I re-add the CallBackHandler Dependency. Should Fix the error.
