### ISSUE TITLE
Double quest complete sounds playing..

### ISSUE THREAD

**Issue by MelchiorGaspar** [donniedice/BLU#3]
Hi.
I think its this addon causing the double quest completion sound to deploy...
It happens twice,
once when i get to the window where you click the button to turn in a quest... 
and it happens a swecond time when I actually click the the complete quest button..
its kinda annoying..

This is happening in World of Warcraft Classic-Era (v1.15.2) with BLU (v1.0.11).
I don't know if it happens in Wrath classic or retail yet I haven't played either of those flavors of WoW in a month or so.

please fix if you can. please and thx.

I am on Windows 11 Pro
EVGA/Nvidia GeForce RTX 3070 Ti 8GB.
Nvidia display drivers v552.22 so up to date.
32GB of RAM..

if I missed any info please let me know... and i will grab it and post it here.

I have the default quest complete sound set to play in BLU and do not mute the default... 
I will post the settings file from BLU...

[BLU_lua.zip](https://github.com/donniedice/BLU/files/15045273/BLU_lua.zip)

**Comment by donniedice** [comment]
Ok. I'ved looked into this. If you turn off BLU, you'll see that this is just how Classic Era functions. I'm not sure at this time what event is being called when the quest window is opened, but I am looking into it. There may be a way I can assist in clearing up this annoyance for you.

**Comment by MelchiorGaspar** [comment]
ooh ok, oops sry... I wasn't sure... so I should have tested with it off too...
I will post this in game bug reporting function too then.
