### ISSUE TITLE
sounds not playing in CATA classic, for level up sounds at least..

### ISSUE THREAD

**Issue by MelchiorGaspar** [donniedice/BLU#4]
The CATA classic update seems to have broke the game a lot..
and for this addon sounds included with it are not playing when a sound should be triggered...
like when I level up... its just silent, so the mute default channel is working it seems...

CATA v4.4.0.54501 just patched in.
using BLU (v1.0.11)

**Comment by donniedice** [comment]
v1.0.12 was just pushed out and should fix this issue. The files have now been updated to support the new Cataclysm Classic client.

**Comment by MelchiorGaspar** [comment]
thx donniedice,
for quick turn around lol :D 
I will test and report back on next level up.
I have it set to Final Fantasy level up sound.

**Comment by donniedice** [comment]
> thx donniedice, for quick turn around lol :D I will test and report back on next level up. I have it set to Final Fantasy level up sound.

You're very welcome! And also thank you so much for reporting issues!

**Comment by MelchiorGaspar** [comment]
I like beta testing and bug reporting..
so my pleasure!


whats this about?
"Removed - Achievements section from [Core_v.lua]"  in v2.0.0 release just now.

does that mean I can't set sounds for the achievements when a sound is suppose to play?

**Comment by donniedice** [comment]
> I like beta testing and bug reporting.. so my pleasure!
> 
> whats this about? "Removed - Achievements section from [Core_v.lua]" in v2.0.0 release just now.
> 
> does that mean I can't set sounds for the achievements when a sound is suppose to play?

All functionality remains intact. Currently there are 3 versions of WoW, and subsequently 3 versions of my Core.lua code. I have Core.lua, for Retail, Core_c.lua for Cataclysm, and Core_v.lua for Vanilla/SoD.

The code for Core_v.lua(Vanilla) had leftovers for playing sounds for Achievement earned, however Achievements do not exist in Vanilla.

**Comment by MelchiorGaspar** [comment]
oooh! ok kool.
thx for the reply.
