### ISSUE TITLE
Can you add random sound choice and make it default?

### ISSUE THREAD

**Issue by StellarHarbour** [donniedice/BLU#5]

**Comment by donniedice** [comment]
Play Random Sound would be a cool feature! I can definitely look into this.

I'm not sure what you mean by 'and make it default' however.

**Comment by StellarHarbour** [comment]
So every player will have it by default instead Minecraft level up sound and if they like it maybe they will check game too

**Comment by donniedice** [comment]
I've added the Random Sound selection to v2.1.1.

**Comment by StellarHarbour** [comment]
Nice, thanks for update, did you thought about critical sound too? 
https://www.curseforge.com/wow/addons/wow-i-crit
I use this addon but listening to one sound for dozens of hours is cursed
