### ISSUE TITLE
Option to have high and low level volumes

### ISSUE THREAD

**Issue by Canguy421** [donniedice/BLU#8]
Your latest change to BLU has made the level up sound really low, example being when I discovered an area and dinged, the discover of the area sound was 3 times louder then the ding sound. previous versions had it more defined "louder" as a level up , same as reputation /achievements. I love the addon and all your better addons, I just prefer hearing it over other game sounds, Thanks for consideration

**Comment by donniedice** [comment]
Okay, I will do another pass on volume levels soon. As far as volume sliders.. that is planned for a future update.

**Comment by donniedice** [comment]
Ok so I have looked into this.. The volume normalization made it so that BLU sounds shouldn't be louder than WoW..
I may do a pass and increase db on the sounds themselves however, you can increase you master volume, and then lower the other sliders.. That will make BLU sounds louder.

**Comment by donniedice** [comment]
Thought I'd give you a heads up. I'm working on v4 and it has volume sliders.

**Comment by donniedice** [comment]
![image](https://github.com/donniedice/BLU/assets/60427166/cb6ad8f0-f8ed-4e97-956b-9f3036766581)
