### ISSUE TITLE
Addon Messages for Default Quest Accept Sound/Welcome Message on entering and leaving Instances

### ISSUE THREAD

**Issue by chasaya** [donniedice/BLU#9]
Since a few versions having the "Quest accepted" sound set to "Default" leads to this message in chat every time i accept a quest:

"defaultQuestAcceptSounds: Interface\Addons\BLU\sounds\quest_accept_default_med.ogg"

This only happens when i have the sound set to "Default"; if i change the sound to anything else, the chat message does not appear.
I have several other sounds set to "Default", those seem to be fine; but i haven't tested each and every setting, so it might be that similar chat messages could occur for other combinations.

Another issue: whenever i enter or leave instanced areas (dungeons, scenarios, raid). the "Welcome" message incl. the update note is displayed. 
Generally, i would greatly appreciate if it would be possible to have a setting where i could deactivate the "Welcome" message for the addon altogether; i have a lot of addons and any possibility to reduce the loadup "spam" is a godsend :). If that can't be done, i would however appreciate if the message could at least be only displayed once per session.

Thanks for the great addon anyway, it made my experience so much better to level up with the Skyrim sound 💯!

**Comment by donniedice** [comment]
v4.0.2 is going to remove the login spam - it is not needed.
Also removed the rest of the debug code. 
Thanks for the positive words and bug reports! I'm glad you like my addon!
